export const URL_API = process.env.API_APP_URL || 'http://localhost:8040/api'
export const TOKEN_KEY = process.env.API_APP_TOKEN_KEY || 'access_token'
export const VUE_APP_KEY_STORE = process.env.VUE_APP_KEY_STORE || 'front-app'
export const TOKEN_EXPIRES = process.env.API_APP_TOKEN_EXPIRES || 'token_api_expires'
export const REFRESH_TOKEN_KEY = process.env.API_APP_REFRESH_TOKEN_KEY || 'token_api_refresh'
export const SECURE_LS_SECRET = process.env.SECURE_LS_SECRET || 's3cr3tPa$$w0rd@123'
export const SECURE_LS_ENCODING = process.env.SECURE_LS_SECRET || 'rc4$$rc4@123'
